name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Update Rust and Cargo version
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # Install dependencies for cross-compilation
    - name: Install dependencies
      run: sudo apt-get install -y gcc-multilib

    # Build for x86_64 architecture
    - name: Build for x86_64
      run: cargo build --release --target=x86_64-unknown-linux-gnu

    # Create binary image for Intel NUC
    - name: Create binary image for Intel NUC
      run: |
        mkdir -p release
        cp target/x86_64-unknown-linux-gnu/release/your_binary release/
        # Add any additional steps to create the binary image here
